# Transform pipeline
# To demonstrate how you can transform SQL Pools
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - main

variables:
  configuration: release
  database: UnitTesting
  azuredatabase: Azure-Data
  artifactname: Database
  azuresyndatabase: AzureSQLPool
  sqlpoolartifactname: AzureSQLPool

stages:

# Transform stage for AzurePool2
- stage: TransformandBuild
  displayName: 'Transform & Build'
  variables:
    variables:
    agentpool: 'Azure DevOps Duet'
    poolstagingarea: $(Build.ArtifactStagingDirectory)\poolstaging2
    sourcepath: $(database)-Data

  pool: $(agentpool)

  jobs:
    - job: 'TransformAzureSQLPool2'
      displayName: 'Transform Tables for AzurePool'
      variables:
        variables:
        tablesfolder: poolstaging2\$(sourcepath)\Tables

      steps:

      - task: CopyFiles@2
        displayName: "Copy files to staging area for SQL Pool"
        # Copies the file to a sub folder in the artifacts directory
        inputs:
          Contents: |
            $(sourcepath)\**
          TargetFolder: '$(poolstagingarea)'
          FlattenFolders: false
          OverWrite: true

      - task: PowerShell@2
        displayName: "Runs PowerShell to add Hash distribution"
        # Adds Hash distribution to Table 1
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            cd..
            cd a
            ls
            cd $(tablesfolder)
            ls
           
            $Old_end = '\);'
            $New_end = ') WITH (DISTRIBUTION = HASH (Column1), CLUSTERED COLUMNSTORE INDEX);'
            $New_end
                       
            (Get-Content "Table1.sql") -replace $Old_end, $New_end  | Set-Content "Table1.sql" 

      - task: PowerShell@2
        displayName: "Runs PowerShell to replace DSP"
        # Renames the .sqlproj file
        # Followed by the PowerShell to replace the Database Schema Provider
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            cd..
            cd a
            cd poolstaging2\$(database)-Data
           
            $Old_DSP = 'Microsoft.Data.Tools.Schema.Sql.Sql140DatabaseSchemaProvider'
            $New_DSP = 'Microsoft.Data.Tools.Schema.Sql.SqlDwDatabaseSchemaProvider'
            
            rename-item UnitTesting-Data.sqlproj AzureSQLPool.sqlproj
            rename-item UnitTesting-Data.publish.xml AzureSQLPool.publish.xml
            
            (Get-Content "AzureSQLPool.sqlproj") -replace $Old_DSP, $New_DSP  | Set-Content "AzureSQLPool.sqlproj"

      - task: VSBuild@1
        displayName: 'Build Azure-Data project'
        # Builds the specific project using the renamed .sqlproj file
        inputs:
          solution: $(poolstagingarea)/$(database)-Data/AzureSQLPool.sqlproj
          configuration: $(configuration)

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Azure SQL database artifact'
        # Publishes the dacpac as part of an artifact within Azure DevOps
        inputs:
          PathtoPublish: '$(poolstagingarea)\$(database)-Data\bin\$(configuration)'
          ArtifactName: $(sqlpoolartifactname)
          publishLocation: 'Container'


- stage: DeployAzurePool
  dependsOn: TransformandBuild
  displayName: 'AzureSQLPool2 Deploy'

  jobs:
    - job: 'Deploy2019'
      displayName: 'Deploy AzureSQLPool'
      variables:
        variables:
        agentpool: 'Azure DevOps Duet'
        dacpacpath: $(System.ArtifactsDirectory)/$(sqlpoolartifactname)
        datadacpacfile: $(dacpacpath)/AzureSQLPool.dacpac

      pool: $(agentpool)
        
      steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Dowload Artifacts'
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          artifactName:  '$(sqlpoolartifactname)'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: SqlAzureDacpacDeployment@1
        displayName: 'Install DACPAC on AzureSQLPool2'
        inputs:
          azureSubscription: '$(vsentsubscriptionb)'
          AuthenticationType: 'server'
          ServerName: 'dtsynapsews.sql.azuresynapse.net'
          DatabaseName: '$(azuresyndatabase)'
          SqlUsername: 'sqladminuser'
          SqlPassword: '$(sqlsapw)'
          deployType: 'DacpacTask'
          DeploymentAction: 'Publish'
          DacpacFile: '$(datadacpacfile)'